### ISSUE TITLE
Webpackが起動しない

### ISSUE THREAD

**Issue by shortBread2329** [shortBread2329/CookHub#1]
`ruby ./bin/webpack serve`
を実行するとVueで実装したフロントエンドが起動する想定だがエラー
エラーログは以下の通り
```
[webpack-cli] Failed to load '/home/ec2-user/environment/CookHub/config/webpack/development.js' config
[webpack-cli] TypeError: Cannot read property 'toWebpackConfig' of undefined
    at Object.<anonymous> (/home/ec2-user/environment/CookHub/config/webpack/development.js:5:30)
    at Module._compile (/home/ec2-user/environment/CookHub/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (/home/ec2-user/environment/CookHub/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WebpackCLI.tryRequireThenImport (/home/ec2-user/environment/CookHub/node_modules/webpack-cli/lib/webpack-cli.js:32:22)
    at loadConfig (/home/ec2-user/environment/CookHub/node_modules/webpack-cli/lib/webpack-cli.js:1536:38)
    at /home/ec2-user/environment/CookHub/node_modules/webpack-cli/lib/webpack-cli.js:1589:42
```

**Comment by shortBread2329** [comment]
一旦最小の起動構成に修正することで対応済みとします。
